Reporting a missing tcldot lirary is no longer performed during configure but in the makefile of the graph-browser.

diff --git a/meta/graph-browser/Makefile.am b/meta/graph-browser/Makefile.am
--- a/meta/graph-browser/Makefile.am
+++ b/meta/graph-browser/Makefile.am
@@ -32,6 +32,12 @@ man_MANS    = graph-browser.1
 CLEANFILES  = graph-browser graph-browser.1
 
 % : %.sh.src Makefile
+	@if [ ! -d $(TCLDOT)/Tcldot ]; then \
+	   echo "Required library \`Tcldot' not found. Please specify its\
+	         location during configuration with the \`--with-tcldot'\
+                 flag." >&2 ;\
+	   exit 1 ;\
+	 fi
 	sed 's@__WISH__@$(WISH)@g;\
 	     s@__TCLDOT__@$(TCLDOT)@g;\
 	     s@__DATADIR__@$(datadir)@g' < $< > $@ && \
