- Number of unit-tests added. - Updated existing tests to reflect code changes. - Local tb and idef files are used for testing. - Number of print statements commented. - ATfprintf(stderr, ... ==> ATwarning(... - baf and raw "notions" replaced by tree(<TREE>) and text(<TEXT>). - open_sdf2_file and open_eqs_file routines merged into open_asdf2_file. - Variable names improved. - Id argument removed.

diff --git a/meta/in-output/test/in-output-test.in b/meta/in-output/test/in-output-test.in
--- a/meta/in-output/test/in-output-test.in
+++ b/meta/in-output/test/in-output-test.in
@@ -5,16 +5,24 @@
 toolbus=__bindir__/toolbus
 datadir=__datadir__
 
+tests=0
+failed=0
+
 call_toolbus () {
   script=$1
+  tests=`expr $tests + 1`
   result=`${toolbus} -I${datadir} ${script} 2>&1`
-  if echo $result | grep -iq failed; then
-    echo ${result}
-    exit 1
+  toolbus_exit=$?
+  if [ $toolbus_exit != 0 ]; then
+    echo "Failed: " $script ": " ${result}
+    failed=`expr $failed + 1`
+  elif echo $result | grep -iq failed; then
+    echo "Failed: " $script ": " ${result}
+    failed=`expr $failed + 1`
   else
-    echo -n "."
+    echo -n .
   fi
-}
+}    
 
 # Test 1. Check whether a non-existing sdf2 module exists.
 call_toolbus in-output-test-1.tb
@@ -35,4 +43,30 @@ rm -f EmptyEqsSection.eqs
 call_toolbus in-output-test-5.tb
 rm -f EmptyEqsSection.eqs
 
+# Test 6. Attempt to open an existing equations section.
+echo "" > TestEqs.eqs
+call_toolbus in-output-test-6.tb
+rm -f TestEqs.eqs
+
+# Test 7. Attempt to open a non-existing equations section.
+call_toolbus in-output-test-7.tb
+
+# Test 8. Attempt to open an existing sdf2 definition.
+echo "module TestSdf" > TestSdf.sdf2
+call_toolbus in-output-test-8.tb
+rm -f TestSdf.sdf2
+
+# Test 9. Attempt to open a non-existing sdf2 section.
+call_toolbus in-output-test-9.tb
+
+# Test 10. Attempt to open an existing sdf2 section in baf.
+call_toolbus in-output-test-10.tb
+
 echo ""
+
+if [ $failed != 0 ]; then
+        echo "FAILED:" $failed "out of" $tests "tests"
+        exit 1
+else
+  echo "All" $tests "tests succeeded"
+fi  
