- Separate parse tables for terms and equations are generated.

diff --git a/meta/tbscripts/test/module-test.in b/meta/tbscripts/test/module-test.in
--- a/meta/tbscripts/test/module-test.in
+++ b/meta/tbscripts/test/module-test.in
@@ -1,7 +1,8 @@
 #! /bin/sh
 #
 #    Meta-Environment - An environment for language prototyping.
-#    Copyright (C) 2000  Stichting Mathematisch Centrum, Amsterdam, The Netherlands. 
+#    Copyright (C) 2000  Stichting Mathematisch Centrum, Amsterdam, 
+#                        The Netherlands. 
 #
 #    This program is free software; you can redistribute it and/or modify
 #    it under the terms of the GNU General Public License as published by
@@ -23,15 +24,23 @@
 toolbus=__bindir__/toolbus
 datadir=__datadir__
 
+tests=0
+failed=0    
+
 call_toolbus () {
   script=$1
+  tests=`expr $tests + 1`   
   result=`${toolbus} -I${datadir} ${script} 2>&1`
-  if echo $result | grep -iq failed; then
-    echo ${result}
-    exit 1
+  toolbus_exit=$?
+  if [ $toolbus_exit != 0 ]; then
+    echo "Failed: " $script ": " ${result}
+    failed=`expr $failed + 1`
+  elif echo $result | grep -iq failed; then
+    echo "Failed: " $script ": " ${result}
+    failed=`expr $failed + 1`
   else
     printf .
-  fi
+  fi             
 }
 
 # Test 1. Attempt to create a non-existing module.
@@ -49,3 +58,11 @@ rm -f ./ExistingModule.sdf2
 call_toolbus new-module-test-3.tb
 
 echo ""
+
+
+if [ $failed != 0 ]; then
+        echo "FAILED:" $failed "out of" $tests "tests"
+        exit 1
+else
+  echo "All" $tests "tests succeeded"
+fi          
