* added a test

diff --git a/error-support/utils/lift-error/Makefile.am b/error-support/utils/lift-error/Makefile.am
--- a/error-support/utils/lift-error/Makefile.am
+++ b/error-support/utils/lift-error/Makefile.am
@@ -11,3 +11,16 @@ lift_error_SOURCES=\
 lift_error_LDADD=\
 	-L${ATERM}/lib -lATerm\
 	-L${top_builddir}/lib -lErrorAPI
+
+ERRORS=example
+EXTRA_DIST=$(wildcard *.ref) $(wildcard *.trm)
+CLEANFILES=$(TESTS)
+
+TESTS=$(foreach e, ${ERRORS}, $e.sh)
+
+%.sh: Makefile
+	@(	echo "#! /bin/sh";\
+		echo "set -e";\
+		echo "./lift-error -i ${srcdir}/$*.trm -o $*.tree";\
+		echo "${ATERM}/bin/atdiff ${srcdir}/$*.ref $*.tree"\
+	) > $@ && chmod +x $@	
