* added support for use as a Unix filter

diff --git a/meta/utils/gen-table.in b/meta/utils/gen-table.in
--- a/meta/utils/gen-table.in
+++ b/meta/utils/gen-table.in
@@ -49,11 +49,11 @@ cat << E_O_USAGE >&2
 Usage: $myname$myargsexplained . . .
 Options:
     -b              write output in Binary AsFix (BAF) format
-    -f              use handcrafted normalizer (\`fast')
+    -f              use handcrafted normalizer ('fast')
     -h              display help information (usage)
     -i _file_       input from _file_ (default: all file arguments)
     -o _file_       output to _file_ (default: _inputfile_.tbl)
-    -s              use compiled specification (\`slow')
+    -s              use compiled specification ('slow')
     -t              write output in plain text format
     -v              verbose mode
     -V              reveal program version (i.e. $myversion)
@@ -151,45 +151,55 @@ case $FASTGEN in
 		TABLEGEN="${PGEN}" ;;
 esac
 
+if [ -z "$Files" ] ; then
+	Files="-"
+fi
+
 for f in $Files
 do
-	# Convert to AsFix1, if necessary
-	dir=`dirname $f`
-	case $f in
-	*.asfix2)
-			file=`basename $f .asfix2`
-			Notify "Converting Asfix2 file $f to AsFix1 file $dir/$file.asfix1"
-			out=$dir/$file.asfix1
-			err=$dir/$file.a2toa1.err
-			if $A2TOA1 < $f > $out 2> $err;
-			then
-				rm -f $err
-			else
-				if [ -f $out -a ! -s $out ]; then rm -f $out; fi
-				echo "a2toa1: error (see $err)"
-				exit 1
-			fi
-			f=$out
-			;;
-	*.asfix1)
-			file=`basename $f .asfix1`
-			;;
-	*.asfix)
-			file=`basename $f .asfix`
-			;;
-	*)
-			echo "$f: input must be AsFix1 or AsFix2" 1>&2
-			continue
-			;;
-	esac
-	for ext in $EXTENSIONS
-	do
-		file=`basename $file $ext`
-	done
+	if [ "$f" = "-" ] ; then
+		# Assume stdin is AsFix1...
+		file="-"
+	        out=${output:-"-"}
+	        err=${TMPDIR:-/var/tmp}/stdin.$$.pgen.err
+	else
+	        # Convert to AsFix1, if necessary
+	        dir=`dirname $f`
+	        case $f in
+	        	*.asfix2)
+			        file=`basename $f .asfix2`
+			        Notify "Converting Asfix2 file $f to AsFix1 file $dir/$file.asfix1"
+			        file=$dir/$file.asfix1
+			        err=$dir/$file.a2toa1.err
+			        if $A2TOA1 < $f > $file 2> $err;
+			        then
+				        rm -f $err
+			        else
+				        if [ -f $file -a ! -s $file ] ; then rm -f $file; fi
+				        echo "a2toa1: error (see $err)"
+				        exit 1
+			        fi
+			        ;;
+			*.asfix1)
+			        file=`basename $f .asfix1`
+			        ;;
+			*.asfix)
+			        file=`basename $f .asfix`
+			        ;;
+			*)
+			        echo "$f: input must be AsFix1 or AsFix2" 1>&2
+			        continue
+			        ;;
+	        esac
+	        for ext in $EXTENSIONS
+	        do
+		        file=`basename $file $ext`
+	        done
+	        out=${output:-$dir/$file.tbl}
+	        err=$dir/$file.pgen.err
+	fi
 
 	Notify "Generating parse table for $f..."
-	out=${output:-$dir/$file.tbl}
-	err=$dir/$file.pgen.err
 	if $TABLEGEN -i $f -o $out 2> $err
 	then
 		rm -f $err
@@ -199,6 +209,8 @@ do
 		exit 2
 	fi
 
-	Notify "Parse table:"
-	Notify `ls -l $out`
+	if [ "$out" != "-" ] ; then
+		Notify "Parse table:"
+		Notify `ls -l $out`
+	fi
 done
